server.port=${PORT:5000}
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://osmadmin:osm12345@osm-cluster.yt7otly.mongodb.net/test?appName=osm-cluster}

# JWT Configurations
jwt.access.secret=${JWT_ACCESS_SECRET:supersecretaccesskey123}
jwt.refresh.secret=${JWT_REFRESH_SECRET:supersecretrefreshkey123}

# File Upload configurations
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Enable Spring Schedulers
spring.task.scheduling.pool.size=2

# Allow circular references
spring.main.allow-circular-references=true
